"""O módulo `exceptions.py` apenas declara as exceções `BoletimError` e `RelatorioError`."""


class BoletimError(Exception):
    pass


class RelatorioError(Exception):
    pass
