"""O módulo `exceptions.py` apenas declara a exceção `BoletimError`."""


class BoletimError(Exception):
    pass
